// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Nov 2020 05:41:36 JST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vpx provides Go bindings for libvpx-1.9.0, the WebM Project VP8/VP9 codec implementation.
*/
package vpx
