// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 06 Nov 2020 05:41:36 JST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package vpx

/*
#cgo pkg-config: vpx
#include <vpx/vpx_encoder.h>
#include <vpx/vpx_decoder.h>
#include <vpx/vp8.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// CodecEncInitVer function as declared in vpx/vpx_encoder.h:732
func CodecEncInitVer(ctx *CodecCtx, iface *CodecIface, cfg *CodecEncCfg, flags CodecFlags, ver int32) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	ciface, cifaceAllocMap := (*C.vpx_codec_iface_t)(unsafe.Pointer(iface)), cgoAllocsUnknown
	ccfg, ccfgAllocMap := cfg.PassRef()
	cflags, cflagsAllocMap := (C.vpx_codec_flags_t)(flags), cgoAllocsUnknown
	cver, cverAllocMap := (C.int)(ver), cgoAllocsUnknown
	__ret := C.vpx_codec_enc_init_ver(cctx, ciface, ccfg, cflags, cver)
	runtime.KeepAlive(cverAllocMap)
	runtime.KeepAlive(cflagsAllocMap)
	runtime.KeepAlive(ccfgAllocMap)
	runtime.KeepAlive(cifaceAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecEncInitMultiVer function as declared in vpx/vpx_encoder.h:764
func CodecEncInitMultiVer(ctx *CodecCtx, iface *CodecIface, cfg *CodecEncCfg, numEnc int32, flags CodecFlags, dsf *Rational, ver int32) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	ciface, cifaceAllocMap := (*C.vpx_codec_iface_t)(unsafe.Pointer(iface)), cgoAllocsUnknown
	ccfg, ccfgAllocMap := cfg.PassRef()
	cnumEnc, cnumEncAllocMap := (C.int)(numEnc), cgoAllocsUnknown
	cflags, cflagsAllocMap := (C.vpx_codec_flags_t)(flags), cgoAllocsUnknown
	cdsf, cdsfAllocMap := dsf.PassRef()
	cver, cverAllocMap := (C.int)(ver), cgoAllocsUnknown
	__ret := C.vpx_codec_enc_init_multi_ver(cctx, ciface, ccfg, cnumEnc, cflags, cdsf, cver)
	runtime.KeepAlive(cverAllocMap)
	runtime.KeepAlive(cdsfAllocMap)
	runtime.KeepAlive(cflagsAllocMap)
	runtime.KeepAlive(cnumEncAllocMap)
	runtime.KeepAlive(ccfgAllocMap)
	runtime.KeepAlive(cifaceAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecEncConfigDefault function as declared in vpx/vpx_encoder.h:795
func CodecEncConfigDefault(iface *CodecIface, cfg *CodecEncCfg, usage uint32) CodecErr {
	ciface, cifaceAllocMap := (*C.vpx_codec_iface_t)(unsafe.Pointer(iface)), cgoAllocsUnknown
	ccfg, ccfgAllocMap := cfg.PassRef()
	cusage, cusageAllocMap := (C.uint)(usage), cgoAllocsUnknown
	__ret := C.vpx_codec_enc_config_default(ciface, ccfg, cusage)
	runtime.KeepAlive(cusageAllocMap)
	runtime.KeepAlive(ccfgAllocMap)
	runtime.KeepAlive(cifaceAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecEncConfigSet function as declared in vpx/vpx_encoder.h:813
func CodecEncConfigSet(ctx *CodecCtx, cfg *CodecEncCfg) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	ccfg, ccfgAllocMap := cfg.PassRef()
	__ret := C.vpx_codec_enc_config_set(cctx, ccfg)
	runtime.KeepAlive(ccfgAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecGetGlobalHeaders function as declared in vpx/vpx_encoder.h:827
func CodecGetGlobalHeaders(ctx *CodecCtx) *FixedBuf {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.vpx_codec_get_global_headers(cctx)
	runtime.KeepAlive(cctxAllocMap)
	__v := NewFixedBufRef(unsafe.Pointer(__ret))
	return __v
}

// CodecEncode function as declared in vpx/vpx_encoder.h:871
func CodecEncode(ctx *CodecCtx, img *Image, pts CodecPts, duration uint, flags EncFrameFlags, deadline uint) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cimg, cimgAllocMap := img.PassRef()
	cpts, cptsAllocMap := (C.vpx_codec_pts_t)(pts), cgoAllocsUnknown
	cduration, cdurationAllocMap := (C.ulong)(duration), cgoAllocsUnknown
	cflags, cflagsAllocMap := (C.vpx_enc_frame_flags_t)(flags), cgoAllocsUnknown
	cdeadline, cdeadlineAllocMap := (C.ulong)(deadline), cgoAllocsUnknown
	__ret := C.vpx_codec_encode(cctx, cimg, cpts, cduration, cflags, cdeadline)
	runtime.KeepAlive(cdeadlineAllocMap)
	runtime.KeepAlive(cflagsAllocMap)
	runtime.KeepAlive(cdurationAllocMap)
	runtime.KeepAlive(cptsAllocMap)
	runtime.KeepAlive(cimgAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecSetCxDataBuf function as declared in vpx/vpx_encoder.h:919
func CodecSetCxDataBuf(ctx *CodecCtx, buf *FixedBuf, padBefore uint32, padAfter uint32) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cbuf, cbufAllocMap := buf.PassRef()
	cpadBefore, cpadBeforeAllocMap := (C.uint)(padBefore), cgoAllocsUnknown
	cpadAfter, cpadAfterAllocMap := (C.uint)(padAfter), cgoAllocsUnknown
	__ret := C.vpx_codec_set_cx_data_buf(cctx, cbuf, cpadBefore, cpadAfter)
	runtime.KeepAlive(cpadAfterAllocMap)
	runtime.KeepAlive(cpadBeforeAllocMap)
	runtime.KeepAlive(cbufAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecGetCxData function as declared in vpx/vpx_encoder.h:947
func CodecGetCxData(ctx *CodecCtx, iter **CodecIter) *CodecCxPkt {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	citer, citerAllocMap := (*C.vpx_codec_iter_t)(unsafe.Pointer(iter)), cgoAllocsUnknown
	__ret := C.vpx_codec_get_cx_data(cctx, citer)
	runtime.KeepAlive(citerAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := NewCodecCxPktRef(unsafe.Pointer(__ret))
	return __v
}

// CodecGetPreviewFrame function as declared in vpx/vpx_encoder.h:962
func CodecGetPreviewFrame(ctx *CodecCtx) *Image {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.vpx_codec_get_preview_frame(cctx)
	runtime.KeepAlive(cctxAllocMap)
	__v := NewImageRef(unsafe.Pointer(__ret))
	return __v
}

// CodecVersion function as declared in vpx/vpx_codec.h:245
func CodecVersion() int32 {
	__ret := C.vpx_codec_version()
	__v := (int32)(__ret)
	return __v
}

// CodecVersionStr function as declared in vpx/vpx_codec.h:271
func CodecVersionStr() string {
	__ret := C.vpx_codec_version_str()
	__v := packPCharString(__ret)
	return __v
}

// CodecVersionExtraStr function as declared in vpx/vpx_codec.h:280
func CodecVersionExtraStr() string {
	__ret := C.vpx_codec_version_extra_str()
	__v := packPCharString(__ret)
	return __v
}

// CodecBuildConfig function as declared in vpx/vpx_codec.h:288
func CodecBuildConfig() string {
	__ret := C.vpx_codec_build_config()
	__v := packPCharString(__ret)
	return __v
}

// CodecIfaceName function as declared in vpx/vpx_codec.h:297
func CodecIfaceName(iface *CodecIface) string {
	ciface, cifaceAllocMap := (*C.vpx_codec_iface_t)(unsafe.Pointer(iface)), cgoAllocsUnknown
	__ret := C.vpx_codec_iface_name(ciface)
	runtime.KeepAlive(cifaceAllocMap)
	__v := packPCharString(__ret)
	return __v
}

// CodecErrToString function as declared in vpx/vpx_codec.h:309
func CodecErrToString(err CodecErr) string {
	cerr, cerrAllocMap := (C.vpx_codec_err_t)(err), cgoAllocsUnknown
	__ret := C.vpx_codec_err_to_string(cerr)
	runtime.KeepAlive(cerrAllocMap)
	__v := packPCharString(__ret)
	return __v
}

// CodecGetError function as declared in vpx/vpx_codec.h:321
func CodecGetError(ctx *CodecCtx) string {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.vpx_codec_error(cctx)
	runtime.KeepAlive(cctxAllocMap)
	__v := packPCharString(__ret)
	return __v
}

// CodecErrorDetail function as declared in vpx/vpx_codec.h:333
func CodecErrorDetail(ctx *CodecCtx) string {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.vpx_codec_error_detail(cctx)
	runtime.KeepAlive(cctxAllocMap)
	__v := packPCharString(__ret)
	return __v
}

// CodecDestroy function as declared in vpx/vpx_codec.h:352
func CodecDestroy(ctx *CodecCtx) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.vpx_codec_destroy(cctx)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecGetCaps function as declared in vpx/vpx_codec.h:361
func CodecGetCaps(iface *CodecIface) CodecCaps {
	ciface, cifaceAllocMap := (*C.vpx_codec_iface_t)(unsafe.Pointer(iface)), cgoAllocsUnknown
	__ret := C.vpx_codec_get_caps(ciface)
	runtime.KeepAlive(cifaceAllocMap)
	__v := (CodecCaps)(__ret)
	return __v
}

// ImageAlloc function as declared in vpx/vpx_image.h:144
func ImageAlloc(img *Image, fmt ImageFormat, dW uint32, dH uint32, align uint32) *Image {
	cimg, cimgAllocMap := img.PassRef()
	cfmt, cfmtAllocMap := (C.vpx_img_fmt_t)(fmt), cgoAllocsUnknown
	cdW, cdWAllocMap := (C.uint)(dW), cgoAllocsUnknown
	cdH, cdHAllocMap := (C.uint)(dH), cgoAllocsUnknown
	calign, calignAllocMap := (C.uint)(align), cgoAllocsUnknown
	__ret := C.vpx_img_alloc(cimg, cfmt, cdW, cdH, calign)
	runtime.KeepAlive(calignAllocMap)
	runtime.KeepAlive(cdHAllocMap)
	runtime.KeepAlive(cdWAllocMap)
	runtime.KeepAlive(cfmtAllocMap)
	runtime.KeepAlive(cimgAllocMap)
	__v := NewImageRef(unsafe.Pointer(__ret))
	return __v
}

// ImageWrap function as declared in vpx/vpx_image.h:167
func ImageWrap(img *Image, fmt ImageFormat, dW uint32, dH uint32, strideAlign uint32, imgData *byte) *Image {
	cimg, cimgAllocMap := img.PassRef()
	cfmt, cfmtAllocMap := (C.vpx_img_fmt_t)(fmt), cgoAllocsUnknown
	cdW, cdWAllocMap := (C.uint)(dW), cgoAllocsUnknown
	cdH, cdHAllocMap := (C.uint)(dH), cgoAllocsUnknown
	cstrideAlign, cstrideAlignAllocMap := (C.uint)(strideAlign), cgoAllocsUnknown
	cimgData, cimgDataAllocMap := (*C.uchar)(unsafe.Pointer(imgData)), cgoAllocsUnknown
	__ret := C.vpx_img_wrap(cimg, cfmt, cdW, cdH, cstrideAlign, cimgData)
	runtime.KeepAlive(cimgDataAllocMap)
	runtime.KeepAlive(cstrideAlignAllocMap)
	runtime.KeepAlive(cdHAllocMap)
	runtime.KeepAlive(cdWAllocMap)
	runtime.KeepAlive(cfmtAllocMap)
	runtime.KeepAlive(cimgAllocMap)
	__v := NewImageRef(unsafe.Pointer(__ret))
	return __v
}

// ImageSetRect function as declared in vpx/vpx_image.h:184
func ImageSetRect(img *Image, x uint32, y uint32, w uint32, h uint32) int32 {
	cimg, cimgAllocMap := img.PassRef()
	cx, cxAllocMap := (C.uint)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.uint)(y), cgoAllocsUnknown
	cw, cwAllocMap := (C.uint)(w), cgoAllocsUnknown
	ch, chAllocMap := (C.uint)(h), cgoAllocsUnknown
	__ret := C.vpx_img_set_rect(cimg, cx, cy, cw, ch)
	runtime.KeepAlive(chAllocMap)
	runtime.KeepAlive(cwAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
	runtime.KeepAlive(cimgAllocMap)
	__v := (int32)(__ret)
	return __v
}

// ImageFlip function as declared in vpx/vpx_image.h:194
func ImageFlip(img *Image) {
	cimg, cimgAllocMap := img.PassRef()
	C.vpx_img_flip(cimg)
	runtime.KeepAlive(cimgAllocMap)
}

// ImageFree function as declared in vpx/vpx_image.h:202
func ImageFree(img *Image) {
	cimg, cimgAllocMap := img.PassRef()
	C.vpx_img_free(cimg)
	runtime.KeepAlive(cimgAllocMap)
}

// CodecDecInitVer function as declared in vpx/vpx_decoder.h:134
func CodecDecInitVer(ctx *CodecCtx, iface *CodecIface, cfg *CodecDecCfg, flags CodecFlags, ver int32) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	ciface, cifaceAllocMap := (*C.vpx_codec_iface_t)(unsafe.Pointer(iface)), cgoAllocsUnknown
	ccfg, ccfgAllocMap := cfg.PassRef()
	cflags, cflagsAllocMap := (C.vpx_codec_flags_t)(flags), cgoAllocsUnknown
	cver, cverAllocMap := (C.int)(ver), cgoAllocsUnknown
	__ret := C.vpx_codec_dec_init_ver(cctx, ciface, ccfg, cflags, cver)
	runtime.KeepAlive(cverAllocMap)
	runtime.KeepAlive(cflagsAllocMap)
	runtime.KeepAlive(ccfgAllocMap)
	runtime.KeepAlive(cifaceAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecPeekStreamInfo function as declared in vpx/vpx_decoder.h:163
func CodecPeekStreamInfo(iface *CodecIface, data string, dataSz uint32, si *CodecStreamInfo) CodecErr {
	ciface, cifaceAllocMap := (*C.vpx_codec_iface_t)(unsafe.Pointer(iface)), cgoAllocsUnknown
	cdata, cdataAllocMap := unpackPUint8String(data)
	cdataSz, cdataSzAllocMap := (C.uint)(dataSz), cgoAllocsUnknown
	csi, csiAllocMap := si.PassRef()
	__ret := C.vpx_codec_peek_stream_info(ciface, cdata, cdataSz, csi)
	runtime.KeepAlive(csiAllocMap)
	runtime.KeepAlive(cdataSzAllocMap)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(cifaceAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecGetStreamInfo function as declared in vpx/vpx_decoder.h:181
func CodecGetStreamInfo(ctx *CodecCtx, si *CodecStreamInfo) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	csi, csiAllocMap := si.PassRef()
	__ret := C.vpx_codec_get_stream_info(cctx, csi)
	runtime.KeepAlive(csiAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecDecode function as declared in vpx/vpx_decoder.h:214
func CodecDecode(ctx *CodecCtx, data string, dataSz uint32, userPriv unsafe.Pointer, deadline int) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cdata, cdataAllocMap := unpackPUint8String(data)
	cdataSz, cdataSzAllocMap := (C.uint)(dataSz), cgoAllocsUnknown
	cuserPriv, cuserPrivAllocMap := userPriv, cgoAllocsUnknown
	cdeadline, cdeadlineAllocMap := (C.long)(deadline), cgoAllocsUnknown
	__ret := C.vpx_codec_decode(cctx, cdata, cdataSz, cuserPriv, cdeadline)
	runtime.KeepAlive(cdeadlineAllocMap)
	runtime.KeepAlive(cuserPrivAllocMap)
	runtime.KeepAlive(cdataSzAllocMap)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecGetFrame function as declared in vpx/vpx_decoder.h:234
func CodecGetFrame(ctx *CodecCtx, iter **CodecIter) *Image {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	citer, citerAllocMap := (*C.vpx_codec_iter_t)(unsafe.Pointer(iter)), cgoAllocsUnknown
	__ret := C.vpx_codec_get_frame(cctx, citer)
	runtime.KeepAlive(citerAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := NewImageRef(unsafe.Pointer(__ret))
	return __v
}

// CodecRegisterPutFrameCb function as declared in vpx/vpx_decoder.h:269
func CodecRegisterPutFrameCb(ctx *CodecCtx, cb CodecPutFrameCbFn, userPriv unsafe.Pointer) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	ccb, ccbAllocMap := cb.PassValue()
	cuserPriv, cuserPrivAllocMap := userPriv, cgoAllocsUnknown
	__ret := C.vpx_codec_register_put_frame_cb(cctx, ccb, cuserPriv)
	runtime.KeepAlive(cuserPrivAllocMap)
	runtime.KeepAlive(ccbAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecRegisterPutSliceCb function as declared in vpx/vpx_decoder.h:310
func CodecRegisterPutSliceCb(ctx *CodecCtx, cb CodecPutSliceCbFn, userPriv unsafe.Pointer) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	ccb, ccbAllocMap := cb.PassValue()
	cuserPriv, cuserPrivAllocMap := userPriv, cgoAllocsUnknown
	__ret := C.vpx_codec_register_put_slice_cb(cctx, ccb, cuserPriv)
	runtime.KeepAlive(cuserPrivAllocMap)
	runtime.KeepAlive(ccbAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}

// CodecSetFrameBufferFunctions function as declared in vpx/vpx_decoder.h:355
func CodecSetFrameBufferFunctions(ctx *CodecCtx, cbGet GetFrameBufferCbFn, cbRelease ReleaseFrameBufferCbFn, cbPriv unsafe.Pointer) CodecErr {
	cctx, cctxAllocMap := (*C.vpx_codec_ctx_t)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	ccbGet, ccbGetAllocMap := cbGet.PassValue()
	ccbRelease, ccbReleaseAllocMap := cbRelease.PassValue()
	ccbPriv, ccbPrivAllocMap := cbPriv, cgoAllocsUnknown
	__ret := C.vpx_codec_set_frame_buffer_functions(cctx, ccbGet, ccbRelease, ccbPriv)
	runtime.KeepAlive(ccbPrivAllocMap)
	runtime.KeepAlive(ccbReleaseAllocMap)
	runtime.KeepAlive(ccbGetAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	__v := (CodecErr)(__ret)
	return __v
}
